### PR TITLE
Proxy support v4

### PR DESCRIPTION
**Pull request by adriangibanelbtactic**
This branch adds support for ZCS multiserver server which have separated proxies and mailboxes.

If you know how to make a better understandable prettify commit or commits you are welcome to do so.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @adriangibanelbtactic ,

Can you add a section to the readme.md to explain how to configure for use with multi-server environment? Thanks!

**Comment by ghost** [comment]
In case there is no user-configuration, at least mention it in the readme.

Also can you add some comments to the code, at least above the newly created method: redirectGETRequestToRemoteServer

Last but not least, would you agree in releasing as GnuGPLv2 instead of v3? The license on the project needs to be put to version 2 some day to stay compatible with Zimbra.

**Comment by adriangibanelbtactic** [comment]
> Can you add a section to the readme.md to explain how to configure for use with multi-server environment?
> Thanks!

I'm not sure if it's needed at all. This will work in both scenarios without having to tweak any of the configuration.

The code handles the multi-server and singleserver scenarios in a transparent manner for the final user.

You only need to make sure that the zimlet+extensions are installed in all of the mailboxes.
That's why I'm going to add a 'local only deploy and undeploy' branch in a few minutes.

**Comment by ghost** [comment]
Code looks OK

**Comment by ghost** [comment]
Well then I guess:
_You only need to make sure that the zimlet+extensions are installed in all of the mailboxes._
or something along that, should go in the readme.

**Comment by adriangibanelbtactic** [comment]
> In case there is no user-configuration, at least mention it in the readme.

Well, I personally don't think it's needed because as a final user I assume any zimlet/extension to work in a multi-server scenario because these are Zimbra supported setups.

But I might add something.

> Also can you add some comments to the code, at least above the newly created method: redirectGETRequestToRemoteServer

I will.

> Last but not least, would you agree in releasing as GnuGPLv2 instead of v3? The license on the project needs to be put to version 2 some day to stay compatible with Zimbra.

There is some code from ZeXtras. Is that GNUGPLv2 or GNUGPLv3?
I'm pretty sure you can downgrade your own code but not external code which was previously GNUGPLv3.

**Comment by ghost** [comment]
I do get questions about multi-server setups every now and then, remember it is usually sysadmins reading the readme, not end-users.

If it says at least it is supported and tested on multi-server, it would help.

**Comment by adriangibanelbtactic** [comment]
> Last but not least, would you agree in releasing as GnuGPLv2 instead of v3?

I prefer the code being GnuGPLv3 instead of GnuGPLv2 because of philosophical reasons.
So Zimbra releasing its server as GnuGPLv2 it's a pity.

Anyways, my answer to your question is: Yes, I agree in releasing as GnuGPLv2.

**Comment by ghost** [comment]
Thanks for your contribution

**Pull request merged**
