### PR TITLE
Installer improvements

### PR DESCRIPTION
**Pull request by adriangibanelbtactic**
Hello Barry,

  We would like to merge some installer improvements back to your repo.
Would you please take a look at them and give us feedback just in case you want some of the commits modified?

Do not hesitate to ask us if you have any doubt.

Thank you very much for your feedback!

### CODE REVIEW

**Comment by ghost** [comment]
Thanks, I will look into this next week.

**Comment by ghost** [comment]
Hello,

I see you changed the suggested install option of the Zimlet.

"Are these zimlets updated in production mode?"
"You are only supposed to choose n if you are a developer"

While what you say is not incorrect, I do not like that, as then I will be seeing a lot of people filing issues
because they do not understand how to deploy a zimlet, flush the cache and/or enable it in the proper COS.

I don't want to see an increase in Github issues.


If it comes to the readme

- can you make a single un-install instruction that works no matter how one installs?
- can you _not_ duplicate the steps on how to download and run the installer?


Thanks!

**Comment by ghost** [comment]
Also, the LibreOffice preview is an experimental feature, meaning I do not recommend to install it if you have over 25 users or so actively using it.

The OnlyOffice is a lot better, but that requires a separate docker/vm. 

So having an --auto option that automagically installs an experimental feature,
is not what I would like to do, rather keeping things on the safe side.

**Comment by adriangibanelbtactic** [comment]
> I see you changed the suggested install option of the Zimlet.
> 
> "Are these zimlets updated in production mode?"
> "You are only supposed to choose n if you are a developer"
> 
> While what you say is not incorrect, I do not like that, as then I will be seeing a lot of people filing issues
> because they do not understand how to deploy a zimlet, flush the cache and/or enable it in the proper COS.
> 
> I don't want to see an increase in Github issues.

I am willing to use the zimlet in a production system.
Deploying it in:
```
/opt/zimbra/zimlets-deployed/_dev/
```
is a no.

I might ending hiding this production build option.

**Comment by adriangibanelbtactic** [comment]
> If it comes to the readme
> 
>     can you make a single un-install instruction that works no matter how one installs?

Yes, the production un-install instructions are already designed to assume there might have been a previous development mode installation.

>     can you not duplicate the steps on how to download and run the installer?
Yes, I think I can do that by adding a _Fetching installer script_ subsection.

**Comment by adriangibanelbtactic** [comment]
> Also, the LibreOffice preview is an experimental feature, meaning I do not recommend to install it if you have over 25 users or so actively using it.
> 
> The OnlyOffice is a lot better, but that requires a separate docker/vm.
> 
> So having an --auto option that automagically installs an experimental feature,
> is not what I would like to do, rather keeping things on the safe side.

My reasoning for having the default LibreOffice preview to be turned on by default was because:
* I assume the LibreOffice preview is the one that comes now by default in Zimbra and not a custom of yours
* So something coming from Zimbra, even labeled as experimental, seems to me more stable than relying in a third party for the preview
* While OnlyOffice might preview Microsoft Office documents (docx, xlsx, ...) it does not preview OpenOffice ones (odt, ods, ...).
* LibreOffice preview enables previewing both Microsoft Office (docx,  xlsx, ...) and Open Office documents.

No problem on falling back to OnlyOffice on this option.
I might ending having a custom branch for our default settings or a custom installer for us. I'm not sure.

**Comment by ghost** [comment]
* I assume the LibreOffice preview is the one that comes now by default in Zimbra and not a custom of yours Well that is a wrong assumption, as the one shipped with Zimbra is a Network Edition Only feature, LibreOffice in WebDAV Client is custom 
    * So something coming from Zimbra, even labeled as experimental, seems to me more stable than relying in a third party for the preview This is incorrect, please try and avoid using LibreOffice, it is just not good enough for rendering documents this way. 
    * While OnlyOffice might preview Microsoft Office documents (docx, xlsx, ...) it does not preview OpenOffice ones (odt, ods, ...). This is why we still offer libreoffice in WebDAV Client... OnlyOffice does convert odt to docx and so on. 
    * LibreOffice preview enables previewing both Microsoft Office (docx, xlsx, ...) and Open Office documents. Yeah, but the quality of that customization, is not something you should deploy in a production environment with more than 25 users. 


No problem on falling back to OnlyOffice on this option. 
I might ending having a custom branch for our default settings or a custom installer for us. I'm not sure. 

That sounds like a good idea!

**Comment by adriangibanelbtactic** [comment]
> LibreOffice preview enables previewing both Microsoft Office (docx, xlsx, ...) and Open Office documents.
> 
> > Yeah, but the quality of that customization, is not something you should deploy in a production environment with more than 25 users.

So why is it so bad?
Does it maybe drain the machine RAM ?

**Comment by ghost** [comment]
Well because it is a Java-CLI wrapper around libre-office that fetches
the document to convert to you Zimbra server (in a temp location). Then it
runs a conversion and returns the converted file.

A cron job make sure the temp files are removed (in case that for whatever
reason fails in Java).

So it is a bit messy, it worked well for me so far, but I have no client
that uses open document formats, so I have never deployed it in an organisation
with a enough load to be confident it is not experimental.


The Only Office integration is much better quality code, only a
few lines of JavaScript in the Zimlet, and no inpact on your Zimbra
server. And with docker it can be deployed cleanly and without a large
time investment. Also it renders better, and shows a progress indication
to the user. For LibreOffice preview, just have to wait, it can take a 
while and there is no feedback in the UI.

I think it would be best if OnlyOffice started supporting open-document-formats.

Off topic, I was an advocate for open-document-formats a decade ago,
so I would prefer to use odt if possible, problems is that the adoption
of odt and all that has remained very low. On top of that I see that document
created 10 years ago in older version of Open Office do not render the same
now as they did back then. 

So for archiving I would use PDF (without Adobe crap) and OnlyOffice works
for making (small) changes on the web. If I where to write a large document
and really need to use an office suite, I would just just LibreOffice.

But you can help, tell me how the LibreOffice preview worked in your organisation
and what you load was, than perhaps we can improve it and remove the `experimental`
tag.

**Comment by ghost** [comment]
OnlyOffice is deployed on a Zimbra install with 650 users.

Also I offered Collabora (= LibreOffice) to my users via Nextcloud, and they
did not like it, they did like the OnlyOffice.

And since OnlyOffice is open-source as well, I do not see why not.

**Comment by adriangibanelbtactic** [comment]
What do you think about changing:

```
echo ""
echo "Are these zimlets installed in production mode?"
echo "You are only supposed to choose n if you are a developer"
echo "If you have trouble or are unsure, choose Y. Y/n:"

if [[ "${IS_AUTO}" == 'YES' ]]
then
    YNZIMLETISPRODUCTION="Y"
else
    read YNZIMLETISPRODUCTION;
fi
```

to:

```
echo ""
echo "Do you want to install the zimlet in an easy mode?"
echo "This way you don't need to setup and configure the zimlet on your own?
echo "If you have trouble or are unsure, choose Y. Y/n:"

if [[ "${IS_AUTO}" == 'YES' ]]
then
    YNZIMLETISPRODUCTION="Y"
else
    read YNZIMLETISPRODUCTION;
fi
```
?

**Comment by ghost** [comment]
Looks good 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by adriangibanelbtactic** [comment]
> Looks good
Nice!

I need to perform some more tests and in 2 or 3 hours I'll tell you to review the pull request once again as if I was submitting it to you again.

**Pull request closed without merging**
